# The source image to start with
FROM ubuntu:22.04

# Your contact info
MAINTAINER wiggal ;ludwig.sporrer@gmx.de

ENV DEBIAN_FRONTEND noninteractive
ENV CONTAINER_TIMEZONE="Europe/Berlin"
RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone

RUN apt-get update
RUN apt-get install -y dialog apt-utils
RUN apt-get upgrade -y
RUN apt-get install -y apache2 php vim cron
RUN apt-get install -y python3
RUN apt-get install -y python3-pip

RUN pip install pyModbusTCP==v0.1.10
RUN pip install pickledb
RUN pip install pytz
RUN pip install xmltodict
RUN pip install requests
RUN pip install NumPy==v1.23.1
RUN pip install ping3


ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_RUN_DIR /home/GEN24/html
ENV APACHE_DOCUMENT_ROOT    /home/GEN24/html

RUN sed -i -e 's#/var/www/#/home/GEN24/html/#' /etc/apache2/apache2.conf
RUN sed -i -e 's#/var/www/html#/home/GEN24/html#' /etc/apache2/sites-available/000-default.conf


# Ladesteuerung bereitstellen
RUN mkdir /home/GEN24
COPY GEN24_Ladesteuerung-main/ /home/GEN24/
RUN chown -R www-data:www-data /home/GEN24

#Cronjobeinträge
RUN echo "# DO NOT EDIT THIS FILE - edit the master and reinstall." >>/var/spool/cron/crontabs/www-data
RUN echo "# (/tmp/crontab.uQN1v1/crontab installed on Wed May 31 19:23:33 2023)" >>/var/spool/cron/crontabs/www-data
RUN echo "# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)" >>/var/spool/cron/crontabs/www-data
RUN echo "# Edit this file to introduce tasks to be run by cron." >>/var/spool/cron/crontabs/www-data
RUN echo "#\n#" >>/var/spool/cron/crontabs/www-data
RUN echo "# m h  dom mon dow   command" >>/var/spool/cron/crontabs/www-data
RUN echo "#*/5 05-20 * * * /home/GEN24/start_LoggingSymoGen24.sh" >>/var/spool/cron/crontabs/www-data
RUN echo "*/5 06-19 * * * /home/GEN24/start_SymoGen24Controller2.sh" >>/var/spool/cron/crontabs/www-data
RUN echo "33 5,8,10,12,14,19 * * * /home/GEN24/start_WeatherDataProvider2.sh" >>/var/spool/cron/crontabs/www-data
RUN echo "8 5,8,10,15,19 * * * /home/GEN24/start_Solarprognose_WeatherData.py.sh" >>/var/spool/cron/crontabs/www-data
RUN echo "### /home/GEN24/Crontab.log abräumen" >>/var/spool/cron/crontabs/www-data
RUN echo "0 5 * * 1 mv /home/GEN24/Crontab.log /home/GEN24/Crontab.log_weg" >>/var/spool/cron/crontabs/www-data

RUN chmod 600 /var/spool/cron/crontabs/www-data
RUN chown www-data:crontab /var/spool/cron/crontabs/www-data

# Run the command on container startup
RUN touch /var/log/cron.log

CMD /etc/init.d/apache2 restart && cron  && tail -f /var/log/cron.log

