version: "3"

services:
    gen24:
        image: wiggal/gen24_ladesteuerung_alpine:latest
        container_name: gen24_ladesteuerung
        restart: always
        ports:
            - 80:80
        volumes:
            - ./CONFIGS/config.ini:/home/GEN24/config.ini
            - ./CONFIGS/config.php:/home/GEN24/html/config.php
            - ./CONFIGS/Crontab.log:/home/GEN24/Crontab.log
            - ./CONFIGS/crontab:/var/tmp/www-data
